version: "3.8"

services:
  postgres_db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
  bot:
    build: .
    depends_on:
      - postgres_db
    command: python3 /code/bot.py
